name: CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./front
          dockerfile: Dockerfile
          push: false

  backend-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.19 ]
        os: [ macos-latest ]
    name: backend-lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: back
          args: --issues-exit-code=0
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

  backend-build:
    runs-on: ubuntu-latest
    needs:
      - backend-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go mod download
      - name: Build
        run: go build -o ./bin/wallet-service ./cmd/wallet-service

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./back
          file: ./Dockerfile
          push: false

  deploy:
    runs-on: ubuntu-latest
    needs:
      - frontend-build
      - backend-build
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/apetrov/glossary
            git pull origin main
            git status
            docker-compose down -v 
            docker-compose up --build -d